version: '3'
services:
  node:
    image: node:latest
    ports:
      - 3000:3000
    volumes:
      - ..:/app
    command: tail -f /dev/null
    
  zerochplus:
    image: zerochplus
    build: ./zerochplus-docker
    ports:
      - 8080:80
    deploy:
      # パフォーマンスに関する設定
      resources:
        limits:
          cpus: '8.0'
          memory: 8G
        reservations:
          cpus: '4.0'
          memory: 4G
